create table tb_content (text_content varchar(255), video_uri varchar(255), id int8 not null, primary key (id));
create table tb_course (id  bigserial not null, img_uri varchar(255), name varchar(255), user_id int8, primary key (id));
create table tb_deliver (id  bigserial not null, correct_count int4, feedback varchar(255), moment TIMESTAMP WITHOUT TIME ZONE, status int4, uri varchar(255), course_id int8, user_id int8, lesson_id int8, primary key (id));
create table tb_enrollment (available boolean not null, enroll_moment TIMESTAMP WITHOUT TIME ZONE, course_id int8 not null, user_id int8 not null, primary key (course_id, user_id));
create table tb_enrollment_lessons_done (enrollment_course_id int8 not null, enrollment_user_id int8 not null, lessons_done_id int8 not null, primary key (enrollment_course_id, enrollment_user_id, lessons_done_id));
create table tb_lesson (id  bigserial not null, position int4, title varchar(255), section_id int8, primary key (id));
create table tb_lessons_done (lesson_id int8 not null, user_id int8 not null, course_id int8 not null, primary key (lesson_id, user_id, course_id));
create table tb_notification (id  bigserial not null, moment TIMESTAMP WITHOUT TIME ZONE, read boolean not null, text varchar(255), user_id int8, primary key (id));
create table tb_reply (id  bigserial not null, body varchar(255), moment TIMESTAMP WITHOUT TIME ZONE, author_id int8, topic_id int8, primary key (id));
create table tb_reply_likes (reply_id int8 not null, user_id int8 not null, primary key (reply_id, user_id));
create table tb_resource (id  bigserial not null, description varchar(255), img_uri varchar(255), position int4, title varchar(255), type int4, course_id int8, primary key (id));
create table tb_role (id  bigserial not null, authority varchar(255), primary key (id));
create table tb_section (id  bigserial not null, description varchar(255), img_uri varchar(255), position int4, title varchar(255), prerequisite_id int8, resource_id int8, primary key (id));
create table tb_task (approval_count int4, description varchar(255), due_date TIMESTAMP WITHOUT TIME ZONE, question_count int4, weight float8, id int8 not null, primary key (id));
create table tb_topic (id  bigserial not null, body TEXT, moment TIMESTAMP WITHOUT TIME ZONE, title varchar(255), reply_id int8, author_id int8, course_id int8, lesson_id int8, primary key (id));
create table tb_topic_likes (topic_id int8 not null, user_id int8 not null, primary key (topic_id, user_id));
create table tb_user (id  bigserial not null, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table tb_content add constraint FKjmc1pmpuex5541jwgb07jm4w0 foreign key (id) references tb_lesson;
alter table tb_course add constraint FK12o9pvd915ge6tdm49g2y8fdv foreign key (user_id) references tb_user;
alter table tb_deliver add constraint FK9ilxpkqqp0ba00brpr525ea3f foreign key (course_id, user_id) references tb_enrollment;
alter table tb_deliver add constraint FKjiuhmgjsr90ptlwi820mecyis foreign key (lesson_id) references tb_lesson;
alter table tb_enrollment add constraint FKk130dj0tg3uu9wqfsu1hkwvok foreign key (course_id) references tb_course;
alter table tb_enrollment add constraint FKq4hfr2xc40iew8vo04h7h9s3w foreign key (user_id) references tb_user;
alter table tb_enrollment_lessons_done add constraint FKdkddoer7gw5u80etanlbiiah6 foreign key (lessons_done_id) references tb_lesson;
alter table tb_enrollment_lessons_done add constraint FKcb5nb1x41roa5ttcf1hba85nf foreign key (enrollment_course_id, enrollment_user_id) references tb_enrollment;
alter table tb_lesson add constraint FKr55u61qpr1cbk0jf474117m1o foreign key (section_id) references tb_section;
alter table tb_lessons_done add constraint FKj2h3q8e6bppp0a3qf5cai3x4f foreign key (user_id, course_id) references tb_enrollment;
alter table tb_lessons_done add constraint FKfkh2tpm5fahc7mkencew2m529 foreign key (lesson_id) references tb_lesson;
alter table tb_notification add constraint FK9ihj3k9lv33u6qd10wq18f482 foreign key (user_id) references tb_user;
alter table tb_reply add constraint FKmac8ai3bigq456vprkpcbbo04 foreign key (author_id) references tb_user;
alter table tb_reply add constraint FK49xc9hx9n1s2cbj4v5nj3pbp2 foreign key (topic_id) references tb_topic;
alter table tb_reply_likes add constraint FK4b9fueljmpwq7mc45sriyyvtw foreign key (user_id) references tb_user;
alter table tb_reply_likes add constraint FKa5dpfalm9mi7ymjo9x0op4c9m foreign key (reply_id) references tb_reply;
alter table tb_resource add constraint FK1pck7tbk62y6xvjpgko6vwu2q foreign key (course_id) references tb_course;
alter table tb_section add constraint FKng09eguc2o4idipwe73mem9v4 foreign key (prerequisite_id) references tb_section;
alter table tb_section add constraint FKd0pidgdjq979nl3un4ryx5mjx foreign key (resource_id) references tb_resource;
alter table tb_task add constraint FKjpirq3tu0wrko6unh5jx5o39i foreign key (id) references tb_lesson;
alter table tb_topic add constraint FKryr3evgujofa1v0ynultqfqi7 foreign key (reply_id) references tb_reply;
alter table tb_topic add constraint FK3877ei5v3120o8al14nsnu7rr foreign key (author_id) references tb_user;
alter table tb_topic add constraint FK4k5vvtjxuor8gmf5967u6mar6 foreign key (course_id) references tb_course;
alter table tb_topic add constraint FKdbxbui164cewmgujgf3yyl0ad foreign key (lesson_id) references tb_lesson;
alter table tb_topic_likes add constraint FKfb0wuh6h0tejfujwejutxac1q foreign key (user_id) references tb_user;
alter table tb_topic_likes add constraint FKjyfkg3xwg9v7k8jeijfvlnc7o foreign key (topic_id) references tb_topic;
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_user (name, email, password) VALUES ('Alex Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ('ROLE_STUDENT');
INSERT INTO tb_role (authority) VALUES ('ROLE_INSTRUCTOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 3);
INSERT INTO tb_course (name, img_Uri, user_Id) VALUES ('Bootcamp HTML', 'https://cdn.pixabay.com/photo/2018/03/22/10/55/training-course-3250007_1280.jpg', 1);
INSERT INTO tb_course (name, img_Uri, user_Id) VALUES ('Bootcamp CCC', 'https://cdn.pixabay.com/photo/2018/03/22/10/55/training-course-3250007_1280.jpg', 2);
INSERT INTO tb_course (name, img_Uri, user_Id) VALUES ('Bootcamp Ddd', 'https://cdn.pixabay.com/photo/2018/03/22/10/55/training-course-3250007_1280.jpg', 3);
INSERT INTO tb_enrollment (user_id, course_id, enroll_Moment, available) VALUES (1, 1, TIMESTAMP WITH TIME ZONE '2020-11-20T13:00:00Z', true);
INSERT INTO tb_enrollment (user_id, course_id, enroll_Moment, available) VALUES (2, 1, TIMESTAMP WITH TIME ZONE '2020-11-20T13:00:00Z', true);
INSERT INTO tb_enrollment (user_id, course_id, enroll_Moment, available) VALUES (1, 3, TIMESTAMP WITH TIME ZONE '2020-11-20T13:00:00Z', true);
INSERT INTO tb_resource (title, description, position, img_Uri, type, course_id) VALUES ('Trilha HTML', 'Trilha principal do curso', 1, 'https://cdn.pixabay.com/photo/2018/03/22/10/55/training-course-3250007_1280.jpg', 1, 1);
INSERT INTO tb_resource (title, description, position, img_Uri, type, course_id) VALUES ('Forum', 'Tire suas dúvidas', 2, 'https://cdn.pixabay.com/photo/2018/03/22/10/55/training-course-3250007_1280.jpg', 2, 1);
INSERT INTO tb_resource (title, description, position, img_Uri, type, course_id) VALUES ('Lives', 'Lives exclusivas para a turma', 3, 'https://cdn.pixabay.com/photo/2018/03/22/10/55/training-course-3250007_1280.jpg', 0, 1);
INSERT INTO tb_section (title, description, position, img_Uri, resource_id, prerequisite_id) VALUES ('Capítulo 1', 'Neste capítulo vamos começar', 1, 'https://cdn.pixabay.com/photo/2018/03/22/10/55/training-course-3250007_1280.jpg', 1, null);
INSERT INTO tb_section (title, description, position, img_Uri, resource_id, prerequisite_id) VALUES ('Capítulo 2', 'Neste capítulo vamos continuar', 2, 'https://cdn.pixabay.com/photo/2018/03/22/10/55/training-course-3250007_1280.jpg', 1, 1);
INSERT INTO tb_section (title, description, position, img_Uri, resource_id, prerequisite_id) VALUES ('Capítulo 3', 'Neste capítulo vamos finalizar', 3, 'https://cdn.pixabay.com/photo/2018/03/22/10/55/training-course-3250007_1280.jpg', 1, 2);
INSERT INTO tb_lesson (title, position, section_id) VALUES ('Aula 1 do capítulo 1', 1, 1);
INSERT INTO tb_content (id, text_Content, video_Uri) VALUES (1, 'Material de apoio: abc', 'https://www.youtube.com/watch?v=sqbqoR-lMf8');
INSERT INTO tb_lesson (title, position, section_id) VALUES ('Aula 2 do capítulo 1', 2, 1);
INSERT INTO tb_content (id, text_Content, video_Uri) VALUES (2, '', 'https://www.youtube.com/watch?v=sqbqoR-lMf8');
INSERT INTO tb_lesson (title, position, section_id) VALUES ('Aula 3 do capítulo 1', 3, 1);
INSERT INTO tb_content (id, text_Content, video_Uri) VALUES (3, '', 'https://www.youtube.com/watch?v=sqbqoR-lMf8');
INSERT INTO tb_lesson (title, position, section_id) VALUES ('Tarefa do capítulo 1', 4, 1);
INSERT INTO tb_task (id, description, question_Count, approval_Count, weight, due_Date) VALUES (4, 'Fazer um trabalho legal', 5, 4, 1.0, TIMESTAMP WITH TIME ZONE '2020-11-25T13:00:00Z');
INSERT INTO tb_lessons_done (lesson_id, user_id, course_id) VALUES (1, 1, 1);
INSERT INTO tb_lessons_done (lesson_id, user_id, course_id) VALUES (2, 1, 1);
INSERT INTO tb_notification (text, moment, read, user_id) VALUES ('Primeiro feedback de tarefa: favor revisar', TIMESTAMP WITH TIME ZONE '2020-12-10T13:00:00Z', true, 1);
INSERT INTO tb_notification (text, moment, read, user_id) VALUES ('Segundo feedback: favor revisar', TIMESTAMP WITH TIME ZONE '2020-12-12T13:00:00Z', true, 1);
INSERT INTO tb_notification (text, moment, read, user_id) VALUES ('Terceiro feedback: favor revisar', TIMESTAMP WITH TIME ZONE '2020-12-14T13:00:00Z', true, 1);
INSERT INTO tb_deliver (uri, moment, status, feedback, correct_Count, lesson_id, user_id, course_id) VALUES ('https://github.com/devsuperior/bds-dslearn', TIMESTAMP WITH TIME ZONE '2020-12-10T10:00:00Z', 0, null, null, 4, 1, 1);
